/// Flutter icons SFFLineAwesome
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SFFLineAwesome
///      fonts:
///       - asset: fonts/SFFLineAwesome.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SFFLineAwesome {
  SFFLineAwesome._();

  static const _kFontFam = 'SFFLineAwesome';
  static const _kFontPkg = null;

  static const IconData list_alt_solid = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus_circle_solid = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_circle_solid = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_solid = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tags_solid = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_friends_solid = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_circle = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comments = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dolly_solid = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hand_holding_usd_solid = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
